version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    container_name: video_streaming_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - "4306:3306"
  web:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: video_streaming
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle
    volumes:
      - ".:/video_streaming"
      - "~/.ssh/:/root/tmp_ssh/"
      - gem_cache:/usr/local/bundle:cached
    command: bash -c "cp -r /root/tmp_ssh/* /root/.ssh/ && bash"
volumes:
  gem_cache:
  db_data:
    driver: local
