default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: db

development:
  <<: *default
  database: video_streaming_db

test:
  <<: *default
  database: video_streaming_db

production:
  <<: *default
  database: your_app_production
  username: your_production_username
  password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>
  host: your_production_host
